### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WolfMaster333** [iSach/UltraCosmetics#106]
Hi my error is i spawn pig and mount something any and spam in my console this error.
[14:54:53 ERROR]: Could not pass event VehicleExitEvent to UltraCosmetics v2.1.5

org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.Entity.mount(Entity.java:1562) [craftbuk
kit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.EntityLiving.mount(EntityLiving.java:172
9) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setPassenger(CraftE
ntity.java:315) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at be.isach.ultracosmetics.v1_8_R3.EntityUtil.setPassenger(EntityUtil.ja
va:34) [UltraCosmetics-2.1.5-RELEASE%20(2).jar:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet$1.run(Pet.java:140) [Ultra
Cosmetics-2.1.5-RELEASE%20(2).jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java
:71) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
23) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at be.isach.ultracosmetics.cosmetics.mounts.Mount$MountListener.onPlayer
ToggleSneakEvent(Mount.java:226) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more

**Comment by Quadri1337** [comment]
U have to delete all your other plugins. You can download them later again. 100% no Joke
Good Luck!

**Comment by iSach** [comment]
Are you still having this error in 2.3.1?

**Comment by iSach** [comment]
If you're still having it, please open a new issue.
