### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by GoNotCougsWA** [iSach/UltraCosmetics#120]
Plugin Version: 2.2.1

Server Version: 1.8.8

Issues: Sounds will not work in the plugin

Error:
 Exception in thread "Craft Scheduler Thread - 41"
[17:13:44 WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v2.2.1 generated an exception while executing task 680
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchFieldError: UI_BUTTON_CLICK
        at be.isach.ultracosmetics.cosmetics.gadgets.Gadget$1.run(Gadget.java:140)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
https://guides.github.com/features/mastering-markdown/
>

**Comment by iSach** [comment]
Fixed in 2.3

**Comment by GoNotCougsWA** [comment]
Thanks
