### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by TheKacprus** [iSach/UltraCosmetics#14]
Hello,
 I set my messages in messages.yml. I don't have any error when server is starting. I found an error when I try select any gadget, effect or everything else in my console. Selected gadget doesn't appear of course. This is error log:
[19:57:09 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.0.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_91]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_91]
Caused by: java.lang.NullPointerException
        at be.isach.ultracosmetics.manager.GadgetManager.equipGadget(GadgetManager.java:263) ~[?:?]
        at be.isach.ultracosmetics.manager.GadgetManager.gadgetSelection(GadgetManager.java:241) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_91]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more

I found theme how to remove this too: https://bukkit.org/threads/could-not-pass-event-inventoryclickevent.283891/

**Comment by iSach** [comment]
Could you please send your Messages.yml?

**Comment by TheKacprus** [comment]
http://pastebin.com/j5vnQayb

**Comment by Spurlex** [comment]
Same error. Seems to happen when I have Buycraft or ChatEX plugin. Sometimes worldedit. 

Only occurs on Ammo purchase.

**Comment by iSach** [comment]
@Spurlex The error above isn't the same, @TheKacprus 's error is about selecting a gadget.

**Comment by iSach** [comment]
Reopen if you want, I close until you reply
