### ISSUE TITLE
Excessive velocity set detected: Stack trace on Hype Cart mount and Black Hole gadget.

### ISSUE THREAD

**Issue by mibby** [iSach/UltraCosmetics#152]
UltraCosmetics dev 20
Paper dev 809.

```
[21:14:19] [Craft Scheduler Thread - 17/WARN]: Excessive velocity set detected: tried to set velocity of entity #1672 to (-1.9469785623683165,-0.0,7.346378323887097).
[21:14:19] [Craft Scheduler Thread - 17/WARN]: java.lang.Exception: Stack trace
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at java.lang.Thread.dumpStack(Unknown Source)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.setVelocity(CraftEntity.java:211)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.MountHypeCart.onUpdate(MountHypeCart.java:19)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.Mount$1.run(Mount.java:118)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:14:19] [Craft Scheduler Thread - 17/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
```
[21:20:26] [Craft Scheduler Thread - 24/WARN]: Excessive velocity set detected: tried to set velocity of entity #446 to (5.178023219631541,0.0,-1.9847443361322803).
[21:20:26] [Craft Scheduler Thread - 24/WARN]: java.lang.Exception: Stack trace
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at java.lang.Thread.dumpStack(Unknown Source)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftEntity.setVelocity(CraftEntity.java:211)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at be.isach.ultracosmetics.util.MathUtils.applyVelocity(MathUtils.java:435)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetBlackHole.onUpdate(GadgetBlackHole.java:78)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget$1.run(Gadget.java:118)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:20:26] [Craft Scheduler Thread - 24/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by iSach** [comment]
Due to PaperSpigot.
I don't know if you can but take a look at config to see if you can remove those velocity things.
