### ISSUE TITLE
(1.9.4) 2.3.4  Squids spawn everywhere

### ISSUE THREAD

**Issue by alekso56** [iSach/UltraCosmetics#156]
They spawn on land, in water, everywhere! >_>

+when players are killed by zombies, they sometimes print pumpling.name

**Comment by iSach** [comment]
Wow. Really strange. I will fix that.

**Comment by iSach** [comment]
I just made some tests. Never saw any Squid on land.

**Comment by alekso56** [comment]
You know, im really stumped at this too, it does not happen when i test with the same setup on windows.
the linux server however crashes with this error sometimes.

Time: 7/16/16 10:36 AM
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.server.v1_9_R2.World.a(World.java:2549)
	at net.minecraft.server.v1_9_R2.SpawnerCreature.a(SpawnerCreature.java:120)
	at net.minecraft.server.v1_9_R2.WorldServer.doTick(WorldServer.java:227)
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:781)
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.server.v1_9_R2.World.a(World.java:2549)
	at net.minecraft.server.v1_9_R2.SpawnerCreature.a(SpawnerCreature.java:120)
	at net.minecraft.server.v1_9_R2.WorldServer.doTick(WorldServer.java:227)

i'll have to do some further tests and get back to you. (the error does not happen when the plugin is removed) (however a lot of skipped invalid entity pumpling and flyingsquid will be printed)

**Comment by iSach** [comment]
I tested it on Mac and Linux and didn't happen

About the crash, I don't ahve the Minecraft source code I don't see how I can use it to fix anything.

**Comment by alekso56** [comment]
Sorry about this, the issue wasn't caused directly by your plugin, but rather some iffy reflection stuff and a heap of vanilla bugs, updating to 1.10.2 resolved all issues.
