### ISSUE TITLE
nothing works, but everything is here

### ISSUE THREAD

**Issue by soladev** [iSach/UltraCosmetics#19]
(Frenchy accent, sorry about that, but i think you understand :P) I have a strange issue: I got the chest in my hotbar, but he doesn't work. So i've tried using the /uc menu command, but: 
  -when i use the "main" argument, the menu appear, with items, but i can move items inside and they doesn't work (it's not due to lag)
  -when i use "gadgets" or "hats" or everything argument, there is any items in the menu, except back and clear all items.

Another weird thing, i can't move the chest in my hotbar (I know it's normal, but with all issues around, it's not really normal :P)

**Comment by iSach** [comment]
Je suis belge (francophone) :p
Pas d'erreurs dans les logs ?

**Comment by soladev** [comment]
Oui, je viens de la voir:
[10:37:40] [Server thread/ERROR]: Error occurred while enabling UltraCosmetics v2.0.3 (Is it up to date?)
java.lang.NoSuchFieldError: ELDER_GUARDIAN
	at be.isach.ultracosmetics.cosmetics.morphs.MorphType.<clinit>(MorphType.java:31) ~[?:?]
	at be.isach.ultracosmetics.Core.setupCosmeticsConfigs(Core.java:686) ~[?:?]
	at be.isach.ultracosmetics.Core.onEnable(Core.java:466) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigotmc-1.8.8-R0.1.jar:git-Spigot-db6de12-d3e0b6f]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]

**Comment by soladev** [comment]
J'ai vu l'autre issue avec l'elder Guardian, mais les entités peuvent spawn sans problème (aucune région WG, et aucun plugin n'interdit le spawn) et les menus sont toujours aussi vides...

**Comment by iSach** [comment]
As-tu la bonne version de Lib's Disguises ?

**Comment by soladev** [comment]
Effectivement la version de Lib's Disguises n'était pas bonne merci! Par contre, maintenant que tout fonctionne, j'ai un crash report :O voici son contenu: http://pastebin.com/EAzWYLPy

**Comment by iSach** [comment]
Ce sera bientôt corrigé
