### ISSUE TITLE
[Dev] ConcurrentModification issue

### ISSUE THREAD

**Issue by JHXSMatthew** [iSach/UltraCosmetics#21]
[21:37:11] [Craft Scheduler Thread - 205/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v2.0.3 generated an exception while executing task 369
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at be.isach.ultracosmetics.run.InvalidWorldManager.run(InvalidWorldManager.java:20)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by iSach** [comment]
I can't get this to disappear. I'm not yet really good in multi-threading :/

**Comment by iSach** [comment]
Fixed

**Comment by JHXSMatthew** [comment]
:) Commit +++++, I wanna merge you (LOL).
