### ISSUE TITLE
Problème lors de la déconnection en ouvrant un coffre

### ISSUE THREAD

**Issue by Delekin** [iSach/UltraCosmetics#221]
Quand on se reconnecte juste après s'être déconnecté pendant l'ouverture d'un coffre, on reste bloqué sur place, sans pouvoir rien faire en plus d'avoir l'erreur suivante:
Could not pass event PlayerQuitEvent to UltraCosmetics v2.3.9
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:384) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1060) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.NetworkManager.handleDisconnection(NetworkManager.java:317) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:175) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
at be.isach.ultracosmetics.cosmetics.treasurechests.TreasureChest.clear(TreasureChest.java:323) ~[?:?]
at be.isach.ultracosmetics.UltraPlayer.removeTreasureChest(UltraPlayer.java:615) ~[?:?]
at be.isach.ultracosmetics.UltraPlayer.clear(UltraPlayer.java:384) ~[?:?]
at be.isach.ultracosmetics.listeners.PlayerListener.onQuit(PlayerListener.java:149) ~[?:?]
at sun.reflect.GeneratedMethodAccessor801.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f326992]
... 12 more

**Comment by iSach** [comment]
Corrigé dans les dernièrs betas :)
