### ISSUE TITLE
Spigot 1.8.8 Problems with Zombie Eggs

### ISSUE THREAD

**Issue by Flayovec** [iSach/UltraCosmetics#222]
Hello, when I use Zombie Spawn Egg it doesnt work and plugin write error in console !

[17:30:25] [Server thread/WARN]: java.lang.NoSuchMethodException: be.isach.ultracosmetics.v1_8_R3.customentities.Pumpling.<init>(net.minecraft.server.v1_8_R3.World)
[17:30:25] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[17:30:25] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityTypes.a(SourceFile:201)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ItemMonsterEgg.spawnCreature(ItemMonsterEgg.java:124)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ItemMonsterEgg.a(ItemMonsterEgg.java:113)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ItemMonsterEgg.interactWith(ItemMonsterEgg.java:53)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:117)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:30:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:30:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:30:25] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:30:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[17:30:25] [Server thread/WARN]: Skipping Entity with id 54

Please fix it and sorry for my bad english ;)

**Comment by shadowcaptain21** [comment]
Same lol but ultracosmetics it's too fun and good plugin XD I just did /summon Zombie   to spawn zombie XD

**Comment by iSach** [comment]
Fixed in last Beta Builds (ci.isach.be)
