### ISSUE TITLE
error InventoryClickEvent

### ISSUE THREAD

**Issue by scabbed** [iSach/UltraCosmetics#232]
hello, error i have , if you dont know it yet, MC 1.11.2, last build UC #53

`[12:29:43] [Server thread/ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.4.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException`

and sometimes this spamming

`[12:57:47] [Server thread/WARN]: [UltraCosmetics] Task #15414 for UltraCosmetics v2.4.0 generated an exception
java.lang.NullPointerException`

**Comment by iSach** [comment]
Can you confirm it still happens in Beta Build #58?

**Comment by scabbed** [comment]
it seems to happen less often but i still it sometimes, and here is other errors/warn i have

WARN

`[10:14:55] [Craft Scheduler Thread - 9/WARN]: java.lang.NullPointerException
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at be.isach.ultracosmetics.v1_11_R1.EntityUtil.sendBlizzard(EntityUtil.java:73)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetBlizzardBlaster.onUpdate(GadgetBlizzardBlaster.java:64)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:141)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:14:55] [Craft Scheduler Thread - 9/WARN]: 	at java.lang.Thread.run(Thread.java:745)`

ERROR :

I was using a gadget then the gadget disapear from inventory and i have this error, when i tried to desactivate it

`[10:15:05] [Server thread/ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.4.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at be.isach.ultracosmetics.cosmetics.Cosmetic.getPlayer(Cosmetic.java:106) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetBlizzardBlaster.onClear(GadgetBlizzardBlaster.java:77) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.Cosmetic.clear(Cosmetic.java:80) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.clear(Gadget.java:173) ~[?:?]
	at be.isach.ultracosmetics.player.UltraPlayer.removeGadget(UltraPlayer.java:187) ~[?:?]
	at be.isach.ultracosmetics.menu.menus.MenuGadgets.toggleOff(MenuGadgets.java:95) ~[?:?]
	at be.isach.ultracosmetics.menu.CosmeticMenu.lambda$open$0(CosmeticMenu.java:159) ~[?:?]
	at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:110) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-stb1.11.jar:git-Spigot-d4f98a3-64277ec]
	... 15 more`

ROCKET WARN :
If you have flight disable on your server, you get kicked for flying with this, thats ok, but after you have that warn that spam the console

`[10:21:11] [Server thread/WARN]: [UltraCosmetics] Task #22380 for UltraCosmetics v2.4.0 generated an exception
java.lang.NullPointerException`

Thanks for the fix

And i can speak french better than english so if you understand french that will be better for me ^^

**Comment by iSach** [comment]
Peux-tu essayer avec la 59 stp ?

**Comment by scabbed** [comment]
yep, je te dirais ça ce soir en rentrant du taff, par contre je ne sais pas si tu as vu mais je peux toujours mettre les gadgets dans les item frame avec le dernier build ?

j'ai essayé op, pas op, gm0 gm1 etc.. je peux les mettre et donc les récupérer facilement

a moins qu'il n'y ait un option que tu as ajouté et que je n'ai pas vu ?

**Comment by iSach** [comment]
La dernière a corrigé ça aussi ^^

**Comment by scabbed** [comment]
ah merci, je te dis ça ce soir alors :)

bon dimanche ^^

**Comment by iSach** [comment]
merci à toi aussi :p

**Comment by scabbed** [comment]
salut, ça marche nickel plus aucun soucis. Je vais le mettre sur mon serveur et je te dirais si j'ai d'autres erreurs quand ton plugin sera maltraité par mes joueurs ^^

merci pour les fix
