### ISSUE TITLE
Bugs in plugin

### ISSUE THREAD

**Issue by MrBrikster** [iSach/UltraCosmetics#265]
I see this error while disabling:
`[20:49:19] [Server thread/ERROR]: Error occurred while disabling UltraCosmetics v2.4.0 (Is it up to date?)
java.lang.IllegalArgumentException: value already present: class net.minecraft.server.v1_11_R1.EntityZombie
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at net.minecraft.server.v1_11_R1.RegistrySimple.a(SourceFile:42) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at net.minecraft.server.v1_11_R1.RegistryMaterials.a(SourceFile:22) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at be.isach.ultracosmetics.v1_11_R1.customentities.CustomEntities.unregisterEntities(CustomEntities.java:99) ~[?:?]
	at be.isach.ultracosmetics.v1_11_R1.Module.disable(Module.java:15) ~[?:?]
	at be.isach.ultracosmetics.UltraCosmetics.onDisable(UltraCosmetics.java:217) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot.jar:git-Spigot-625bc00-b5f7b6d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

Also, after selecting gadgets without ammo, when you selects an other cosmetic (not gadget), buying ammo menu is opening.

**Comment by MrBrikster** [comment]
Also, after selecting gadgets without ammo, when you selects an other cosmetic (not gadget), buying ammo menu is opening. - doesn't fixed.
