### ISSUE TITLE
UltraCosmetics... mess...? A big glitch...?

### ISSUE THREAD

**Issue by PgBiel** [iSach/UltraCosmetics#27]
Hey, so, um, I recently posted a issue about gadgets/effects/etc not working on a world I wanted it to. Okay. Then I found the solution by myself and closed it. Then I edited the config and everything worked normally. However, I edited the config again and set TreasureChests to enabled and PetRenaming to enabled and then when I restarted the server, the Cosmetics chest wasnt opening. Then I checked console and it said that it couldnt load UltraCosmetics, and a buncha other stuff but I couldnt copy because the console got spammed because of another plugin starting, and then I checked the plugin config. BOOM. The config was ... Idk how I say that. Simply, most of it was deleted.
Here, the paste:
http://paste.ubuntu.com/14429735/

**Comment by iSach** [comment]
I can't help without the error on the console.

Take it in logs files.

**Comment by PgBiel** [comment]
Here, thats all I got.
[11:33:53] [Server thread/ERROR]: Error occurred while enabling UltraCosmetics v2.0.3 (Is it up to date?)
java.lang.NullPointerException
	at be.isach.ultracosmetics.Core.onEnable(Core.java:431) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1078) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:237) [spigot.jar:git-Spigot-d97e08b-880a532]
	at gyurix.spigotlib.features.LongerChat$AsyncCommandExecutionAvoid.run(LongerChat.java:87) [SpigotLib.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]

**Comment by PgBiel** [comment]
Uh, I think I know what the problem is, but still take a look just in case. If its what im thinking...

**Comment by iSach** [comment]
What do you think the problem is?

**Comment by rj0495** [comment]
He used the /reload command and LongerChat Failed to load which caused the NPE.

**Comment by iSach** [comment]
Okay, thanks @rj0495

**Comment by rj0495** [comment]
NP
