### ISSUE TITLE
Error when purchasing Ammo

### ISSUE THREAD

**Issue by Spurlex** [iSach/UltraCosmetics#28]
```
[19:46:38] [Server thread/ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.0.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1633) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot.jar:git-PaperSpigot-a55011e-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget$GadgetListener.onInventoryClickAmmo(Gadget.java:363) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor286.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-PaperSpigot-a55011e-07c3001]
	... 15 more
```

**Comment by rj0495** [comment]
You don't have Vault Loaded?

**Comment by Spurlex** [comment]
Yes I do.

**Comment by iSach** [comment]
Do you have an economy plugin loaded?

**Comment by Spurlex** [comment]
Yes. We have the economy plugin we made. It has worked previously but clashed with certain plugins (Buycraft?) and certain configs which we cant tell which caused. But now it isn't working and we have no idea why.

**Comment by iSach** [comment]
Is your custom plugin hooking well into Vault?
