### ISSUE TITLE
GadgetTsunami ConcurrentModificationException

### ISSUE THREAD

**Issue by NLthijs48** [iSach/UltraCosmetics#287]
GadgetTsunami [loops through the entities](https://github.com/iSach/UltraCosmetics/blob/master/core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetTsunami.java#L56) in a world inside an async task, while the main thread might modify this list at the same time. This causes a ConcurrentModificationException:
```
java.util.ConcurrentModificationException: [UltraCosmetics] Plugin UltraCosmetics v2.4.4 generated an exception while executing task 703709
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at org.bukkit.craftbukkit.v1_11_R1.CraftWorld.getEntities(CraftWorld.java:621)
    at be.isach.ultracosmetics.cosmetics.gadgets.GadgetTsunami$1.run(GadgetTsunami.java:56)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Next to this the [World#getNearbyEntities()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getNearbyEntities(org.bukkit.Location,%20double,%20double,%20double)) method is a lot better to use than the [World#getEntities()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#getEntities()) method, because you are only interested in entities that are close to the player.

**Comment by iSach** [comment]
Thanks for your report, didn't see there was a getNearbyEntities() in World thought it was only in Entity ^^
it's fixed :p
