### ISSUE TITLE
GadgetPortalGun: Cannot measure distance between worldA and worldB

### ISSUE THREAD

**Issue by NLthijs48** [iSach/UltraCosmetics#290]
The following error appears in the console with UltraCosmetics 2.4.4:
```
java.lang.IllegalArgumentException: Cannot measure distance between worldA and worldB
    at org.bukkit.Location.distanceSquared(Location.java:456)
    at org.bukkit.Location.distance(Location.java:439)
    at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPortalGun.onUpdate(GadgetPortalGun.java:163)
    at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:145)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Looking at [the code](https://github.com/iSach/UltraCosmetics/blob/master/core/src/main/java/be/isach/ultracosmetics/cosmetics/gadgets/GadgetPortalGun.java#L163) the following triggers the error:

1. Place a blue portal
1. Place a red portal (still the same world)
1. Teleport to another world
1. GadgetPortalGun performs an update:
    1. Checks if red and blue are in the same world, which they are
    1. Tries to check if the player is standing in the red or blue portal
    1. Measures distance from the player to the portal
    1. Get the above exception because the player is in another world than the portals

(I recently created [this](https://github.com/NLthijs48/ErrorSink) so I get notified about all warnings/errors on my server)

**Comment by iSach** [comment]
Fixed thanks for report
