### ISSUE TITLE
Nyan Sheep mount server crash

### ISSUE THREAD

**Issue by jensuenk** [iSach/UltraCosmetics#372]
### What steps will reproduce the issue?  
1. Riding the nyan sheep

### What was supposed to happen?
No crash
### What happened? 
Server crash when riding the nyan sheep for 1min
### What version of UltraCosmetics are you using?  
2.4.9
### What Spigot version are you using? Paste the output of /version below.  
[22:34:55 INFO]: This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
[22:34:55 INFO]: Checking version, please wait...
[22:34:57 INFO]: You are 210 version(s) behind
### What plugins do you have installed? Paste the output of /plugins below.  
[22:33:56 INFO]: Plugins (37): BlockParticles, Essentials, PlaceholderAPI, PlugMan, NametagEdit, BuycraftX, MessageAnnouncer, Votifier, EasyBackup, MVdWPlaceholderAPI, Treasures, FastAsyncWorldEdit, DeluxeTags, PermissionsEx, TreasuresAddon-RecentFind, FeatherBoard, Top, SuperbVote, ViaVersion, ItemJoin, Vault, MyCommand, EssentialsSpawn, ViaBackwards, TitleManager, WorldEdit, ProtocolLib, WorldGuard, DeluxeChat, LibsDisguises, Citizens, MiniaturePets, UltraCosmetics, ArmorStandTools, HolographicDisplays, BossShopPro, LimitedUses
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
Time: 1/7/18 10:26 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraft.server.v1_11_R1.PathEntity.a(SourceFile:63)
	at net.minecraft.server.v1_11_R1.NavigationAbstract.m(SourceFile:248)
	at net.minecraft.server.v1_11_R1.NavigationAbstract.l(SourceFile:184)
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:661)
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037)
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
	at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158)
	at net.minecraft.server.v1_11_R1.EntityAnimal.n(EntityAnimal.java:24)
	at net.minecraft.server.v1_11_R1.EntitySheep.n(EntitySheep.java:68)
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631)
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606)
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432)
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618)
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.v1_11_R1.PathEntity.a(SourceFile:63)
	at net.minecraft.server.v1_11_R1.NavigationAbstract.m(SourceFile:248)
	at net.minecraft.server.v1_11_R1.NavigationAbstract.l(SourceFile:184)
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:661)
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2037)
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
	at net.minecraft.server.v1_11_R1.EntityAgeable.n(EntityAgeable.java:158)
	at net.minecraft.server.v1_11_R1.EntityAnimal.n(EntityAnimal.java:24)
	at net.minecraft.server.v1_11_R1.EntitySheep.n(EntitySheep.java:68)
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631)
	at net.minecraft.server.v1_11_R1.World.h(World.java:1606)

-- Entity being ticked --
Details:
	Entity Type: minecraft:sheep (net.minecraft.server.v1_11_R1.EntitySheep)
	Entity ID: 47566
	Entity Name: §cMexicanTwinky's nyan sheep
	Entity's Exact location: -93.17, 4.00, -2.63
	Entity's Block location: World: (-94,4,-3), Chunk: (at 2,0,13 in -6,-1; contains blocks -96,0,-16 to -81,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.22, -0.08, 0.10
	Entity's Passengers: [EntityPlayer['MexicanTwinky'/29640, l='Hub', x=-93.17, y=4.62, z=-2.63](MexicanTwinky at -93.17449839701374,4.6249999642372135,-2.6279858826763896)]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432)
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618)

-- Affected level --
Details:
	Level name: Hub
	All players: 1 total; [EntityPlayer['MexicanTwinky'/29640, l='Hub', x=-93.17, y=4.62, z=-2.63](MexicanTwinky at -93.17449839701374,4.6249999642372135,-2.6279858826763896)]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-103,8,-33), Chunk: (at 9,0,15 in -7,-3; contains blocks -112,0,-48 to -97,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 86587516 game time, 5000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 33585 (now: false), thunder time: 150130 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814)
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:748)
### Any additional information that you would like to provide that may be relevant to the issue?
This only happend once

**Comment by iSach** [comment]
If this is still not working on 2.5.1, please re-open the issue.
