### ISSUE TITLE
Ultra Cosmetics making server crash.

### ISSUE THREAD

**Issue by TheViperShow** [iSach/UltraCosmetics#441]
### What steps will reproduce the issue?  
Install UltraCosmetics v2.4.11

### What was supposed to happen?

Player using ultra cosmetics pets.

### What happened? 

Got errors in the console. up to 100-200 error per second making console+server crash.

### What version of UltraCosmetics are you using?  
2.4.11

### What Spigot version are you using? Paste the output of /version below.  

PaperSpigot-1.12.2(Latest build)

### What plugins do you have installed? Paste the output of /plugins below.  

LuckPerms, WorldEdit, BungeeGuard, ServerSelectorX, ViaVersion, Vault, WorldGuard, ProtocolLib, CustomPayloadFixer, Essentials, EssentialsGeoIP, EssentialsChat, ExtraContexts, HolographicDisplays, EssentialsSpawn, AuthMe

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[18:18:00] [Craft Scheduler Thread - 175/WARN]: java.lang.Throwable
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.spigotmc.ActivationRange.checkIfActive(ActivationRange.java:288)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1626)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:256)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:423)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.MountMoltenSnake.onUpdate(MountMoltenSnake.java:56)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.Mount.run(Mount.java:101)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:18:00] [Craft Scheduler Thread - 175/ERROR]: stopTiming called async for checkIfActive
[18:18:00] [Craft Scheduler Thread - 175/WARN]: java.lang.Throwable
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.spigotmc.ActivationRange.checkIfActive(ActivationRange.java:288)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1626)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:256)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:423)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.MountMoltenSnake.onUpdate(MountMoltenSnake.java:56)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.Mount.run(Mount.java:101)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:18:00] [Craft Scheduler Thread - 175/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:18:00] [Craft Scheduler Thread - 175/ERROR]: stopTiming called async for checkIfActive
```
### Any additional information that you would like to provide that may be relevant to the issue?

that thing is showing up to 200 per second. server can't handle that much.

**Comment by iSach** [comment]
Please try again with latest UC version.

**Comment by datatags** [comment]
Probably fixed when async tasks were changed to sync.
