### ISSUE TITLE
Particle Menu no longer works on 2.5.0

### ISSUE THREAD

**Issue by Germanode** [iSach/UltraCosmetics#443]
### What steps will reproduce the issue?  
1. Install UltraCosmetics 2.5.0 on Paper 1.12.2
2. Do /uc menu main and click on particle effects OR  do /uc menu effects
3. Error

### What was supposed to happen?
The particle menu should open. It doesnt.

### What happened? 
![Screenshot_38](https://user-images.githubusercontent.com/17865871/63272389-416f2300-c29c-11e9-9e5c-5c66a5cb3508.png)

### What version of UltraCosmetics are you using?  
2.5.0

### What Spigot version are you using? Paste the output of /version below.  
1.12.2 Paper - Latest

### What plugins do you have installed? Paste the output of /plugins below.  

![Screenshot_39](https://user-images.githubusercontent.com/17865871/63272274-108eee00-c29c-11e9-8795-5632efe84e89.png)

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
> [14:08:14 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1618]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98) ~[patched_1.12.2.jar:git-Paper-1618]
at be.isach.ultracosmetics.util.UCMaterial.parseItem(UCMaterial.java:1587) ~[?:?]
at be.isach.ultracosmetics.util.UCMaterial.parseItem(UCMaterial.java:1574) ~[?:?]
at be.isach.ultracosmetics.util.ItemFactory.create(ItemFactory.java:31) ~[?:?]
at be.isach.ultracosmetics.menu.CosmeticMenu.open(CosmeticMenu.java:106) ~[?:?]
at be.isach.ultracosmetics.menu.CosmeticMenu.open(CosmeticMenu.java:48) ~[?:?]
at be.isach.ultracosmetics.menu.menus.MenuMain.lambda$putItems$0(MenuMain.java:81) ~[?:?]
at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor615.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
... 15 more
```

**Comment by iSach** [comment]
Hello, can you send your config please?

**Comment by Germanode** [comment]
I used the default one. Regenerated it. I removed the old config file before updating.

**Comment by iSach** [comment]
Can you try again with 2.5.1 please?

**Comment by iSach** [comment]
Closed due to no response. Please re-open if it still happens!
