### ISSUE TITLE
Emotes menu not opening

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#457]
### What steps will reproduce the issue?  
1. Open main UC menu
2. Click on the emotes icon (or directly type /uc menu emotes)

### What was supposed to happen?
The emotes menu should open

### What happened? 
I get an error (see below) on the console and nothing happens

### What version of UltraCosmetics are you using?  
2.5.5

### What Spigot version are you using? Paste the output of /version below.  
This server is running CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
PlaceholderAPI, NametagEdit, EntityDetection, WooMinecraft, ViaVersion, BuycraftX, Multiverse-Core, LibsDisguises, PermissionsEx, MyCommand, Essentials, UltraCosmetics

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
> [19:04:54 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.5.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-da42974-8f47214]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-da42974-8f47214]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-da42974-8f47214]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1878) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-da42974-8f47214]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-da42974-8f47214]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-da42974-8f47214]
at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
at be.isach.ultracosmetics.util.ItemFactory.rename(ItemFactory.java:70) ~[?:?]
at be.isach.ultracosmetics.menu.CosmeticMenu.open(CosmeticMenu.java:223) ~[?:?]
at be.isach.ultracosmetics.menu.CosmeticMenu.open(CosmeticMenu.java:48) ~[?:?]
at be.isach.ultracosmetics.menu.menus.MenuMain.lambda$putItems$0(MenuMain.java:81) ~[?:?]
at be.isach.ultracosmetics.menu.menus.MenuMain$$Lambda$482.00000000C0533DF0.run(Unknown Source) ~[?:?]
at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133) ~[?:?]
at sun.reflect.GeneratedMethodAccessor666.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-da42974-8f47214]
... 15 more
```

**Comment by iSach** [comment]
Does it still happen on 2.5.7?

**Comment by Elric02** [comment]
> Does it still happen on 2.5.7?

Yep, exact same error on 2.5.7, server now running Paper 1.15.1

**Comment by datatags** [comment]
Sounds like a config issue, please regenerate your config and re-open if it's still an issue.
