### ISSUE TITLE
UltraCosmetics crashes when using the gadget "Disco Ball."

### ISSUE THREAD

**Issue by Thobov** [iSach/UltraCosmetics#462]
### What steps will reproduce the issue?  
1. Open the gadgets menu.
2. Activate / Select "Disco Ball."
3. Use the gadget "Disco Ball."

### What was supposed to happen?
Normally when a person uses the gadget "Disco Ball" it should only display the gadget and the player should dance around automatically.
### What happened? 
The gadget works except the automatic jumping and the server console log is being spammed over and over again with the exact same error. After using the gadget UltraCosmetics has crashed and is unusable until server restart.
### What version of UltraCosmetics are you using?  
2.5.5
### What Spigot version are you using? Paste the output of /version below.  
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  
BannerBoard*, Citizens, CorpseReborn*, DamageIndicator, EmptyWorldGenerator*, Essentials, EssentialsChat, EssentialsSpawn, HideItem*, HolographicDisplays, LauncherX*, LibsDisguises, LiteBans*, LuckPerms, Multiverse-Core, NoFireworkDamage*, OnJoin*, ProtocolLib, ServerSelectorX*, SimpleAutoBroadcast*, SSX-Connector*, TigerReports*, TigerReportsSupports*, UltraCosmetics, Vault, ViaBackwards*, ViaRewind*, ViaVersion*, WorldEdit
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[UltraCosmetics] Plugin UltraCosmetics v2.5.5 generated an exception while executing task 144054
java.lang.IllegalStateException: Asynchronous getNearbyEntities!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1157) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1147) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1138) ~[patched_1.14.4.jar:git-Paper-226]
at be.isach.ultracosmetics.cosmetics.gadgets.GadgetDiscoBall.onUpdate(GadgetDiscoBall.java:102) ~[?:?]
at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:142) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
### Any additional information that you would like to provide that may be relevant to the issue?
I tested the plugin with the exact same settings on a different server without all the plugins and I still get the error spammed in my server console. This is not an plugin incompatibility issue. This is what I think an Paper-Spigot compatibility issue. On earlier version of Paper this error also occurs. iSach, I want to thank you for reading this issue and for your time. I also appreciate your work very much! Regards, Thomas.

**Comment by datatags** [comment]
Fixed at some point by removing most async calls.
