### ISSUE TITLE
When I use the Paint Gun and the blocks are not placed and I throw the following error or log into the console.

### ISSUE THREAD

**Issue by ghost** [iSach/UltraCosmetics#463]
[ERROR] Could not pass event ProjectileHitEvent to UltraCosmetics v2.5.6

org.bukkit.event.EventException

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:760) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.EntityProjectile.t_(EntityProjectile.java:157) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.EntityEnderPearl.t_(EntityEnderPearl.java:88) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoSuchFieldError: org/bukkit/Material.WHITE_WOOL

at be.isach.ultracosmetics.util.BlockUtils.getBlockByColor(BlockUtils.java:328) ~[?:?]

at be.isach.ultracosmetics.util.BlockUtils.getBlockByColor(BlockUtils.java:258) ~[?:?]

at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPaintballGun.onProjectileHit(GadgetPaintballGun.java:106) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

... 15 more

**Comment by iSach** [comment]
Should be fixed in 2.5.7
