### ISSUE TITLE
MC client crash upon renaming pet

### ISSUE THREAD

**Issue by SauFey** [iSach/UltraCosmetics#465]
### What steps will reproduce the issue?  
1. 
2. 
3. 

### What was supposed to happen?
Player wants to put a name on his pet.
### What happened? 
On selecting Name your pet, the players MC client crashes.
### What version of UltraCosmetics are you using?  
UltraCosmetics v2.5.6
### What Spigot version are you using? Paste the output of /version below.  
git-Paper-225 1.14.4-R0.1-SNAPSHOT
### What plugins do you have installed? Paste the output of /plugins below.  
AuctionHouse, Autorank, BuycraftX, ChestShop, ChestShop-LegacyIds, ClearLag, CommandTimer*, CoreProtect, CrateReloaded, DeluxeChat, DeluxeJoin, DeluxeMenus, DeluxeTags*, DiscordSRV, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, HeadDatabase*, HolographicDisplays, HolographicScoreboard*, ID-Library, Jobs, LWC, mcMMO, MessageAnnouncer, Multiverse-Core*, MyCommand, OnlyProxy*, PacketListenerApi*, PermissionsEx*, PlaceholderAPI*, PluginLibrary, PremiumVanish, ProtocolLib, QuickBoard*, ServerSigns, SpigotLib, TAB, TokenManager, Towny, UltraCosmetics, Vault, ViaVersion*, Votifier, VotingPlugin, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
10:57:15: java.lang.NullPointerException 
10:57:15: > at be.isach.ultracosmetics.cosmetics.pets.Pet.run(Pet.java:115) 
10:57:15: > at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) 
10:57:15: > at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) 
10:57:15: > at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) 
10:57:15: > at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) 
10:57:15: > at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) 
10:57:15: > at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) 
10:57:15: > at java.lang.Thread.run(Thread.java:748) 
10:57:15: > [UltraCosmetics] Plugin UltraCosmetics v2.5.6 generated an exception while executing task 364583 
java.lang.IllegalStateException: Asynchronous entity add! 
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-225] 
at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:1125) ~[patched_1.14.4.jar:git-Paper-225] 
at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:1062) ~[patched_1.14.4.jar:git-Paper-225] 
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.addEntity(CraftWorld.java:1878) ~[patched_1.14.4.jar:git-Paper-225] 
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawn(CraftWorld.java:1885) ~[patched_1.14.4.jar:git-Paper-225] 
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawn(CraftWorld.java:1465) ~[patched_1.14.4.jar:git-Paper-225] 
at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.spawnEntity(CraftWorld.java:751) ~[patched_1.14.4.jar:git-Paper-225] 
at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:87) ~[?:?] 
at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:63) ~[?:?] 
at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:55) ~[?:?] 
at be.isach.ultracosmetics.player.profile.CosmeticsProfile.loadToPlayer(CosmeticsProfile.java:127) ~[?:?] 
at be.isach.ultracosmetics.player.profile.CosmeticsProfileManager.initForPlayer(CosmeticsProfileManager.java:56) ~[?:?] 
at be.isach.ultracosmetics.listeners.PlayerListener$1.run(PlayerListener.java:73) ~[?:?] 
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-225] 
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-225] 
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-225] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by datatags** [comment]
Can't reproduce, maybe it was fixed when most of the async tasks were changed to sync?
