### ISSUE TITLE
Could not pass event PlayerDeathEvent to UltraCosmetics v2.5.5

### ISSUE THREAD

**Issue by cwchristerw** [iSach/UltraCosmetics#467]
### What steps will reproduce the issue?  
I dont know any way to reproduce

### What was supposed to happen?
Nothing

### What happened?
Multiple Could not pass event PlayerDeathEvent to UltraCosmetics v2.5.5 errors in log dont know what causes them but previously hadnt seen them.

### What version of UltraCosmetics are you using?  
2.5.5

### What Spigot version are you using? Paste the output of /version below.  
This server is running CraftBukkit version git-Spigot-1981d55-3e7b386 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (45): CoreProtect, PetShop, dynmap, BannerBuilder, WorldEdit, Skript, PlaceholderAPI, ClearLag, PlugMan, SkQuery, WorldGuard, PermissionsEx, NoteBlockAPI, ViaVersion, Vault, DeluxeSlime, JukeBox, Essentials, FabledSkyBlock, ProtocolLib, Multiverse-Core, LibsDisguises, Citizens, Sentinel, Images, EssentialsProtect, Multiverse-Inventories, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, TAB, Multiverse-Portals, MineResetLite, ServerListPlus, EssentialsSpawn, GriefPrevention, BlockParticles, UltraCosmetics, Matrix, HolographicDisplays, GriefPreventionDynmap, Multiverse-NetherPortals, BetterRTP, HolographicScoreboard, TouchscreenHolograms

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
24.12 12:35:01 [Server] Server thread/ERROR Could not pass event PlayerDeathEvent to UltraCosmetics v2.5.5
24.12 12:35:01 [Server] INFO org.bukkit.event.EventException: null
24.12 12:35:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:726) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.die(EntityPlayer.java:519) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.die(EntityHumanNPC.java:168) ~[?:?]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1169) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.damageEntity(EntityHuman.java:769) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.damageEntity(EntityPlayer.java:674) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:142) ~[?:?]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:242) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.livingEntityBaseTick(EntityHumanNPC.java:320) ~[?:?]
24.12 12:35:01 [Server] INFO at net.citizensnpcs.nms.v1_14_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:415) ~[?:?]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1067) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:969) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:814) [spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO at java.lang.Thread.run(Thread.java:835) [?:?]
24.12 12:35:01 [Server] INFO Caused by: java.lang.NullPointerException
24.12 12:35:01 [Server] INFO at be.isach.ultracosmetics.player.UltraPlayer.clear(UltraPlayer.java:352) ~[?:?]
24.12 12:35:01 [Server] INFO at be.isach.ultracosmetics.listeners.PlayerListener.onDeath(PlayerListener.java:216) ~[?:?]
24.12 12:35:01 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
24.12 12:35:01 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
24.12 12:35:01 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
24.12 12:35:01 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
24.12 12:35:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-3e7b386]
24.12 12:35:01 [Server] INFO ... 21 more
```

**Comment by cwchristerw** [comment]
Might happen when NPC is die.

**Comment by A248** [comment]
I have the same console report, **but I do not have Citizens installed**, so Citizens does not show in my stacktrace.

At first I thought, what does UltraCosmetics use the PlayerDeathEvent for anyway? Well, as you can see [here](https://github.com/iSach/UltraCosmetics/blob/f4115bdf9e3c1ef0bb6e46332d2ce56ef0185b1d/core/src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java#L247), UltraCosmetics just clears item-based cosmetics, such as suits and gadgets.

Since my players are invulnerable in the Hub world, I don't expect this to be an issue for me.

**Comment by A248** [comment]
Specifically, the issue is that the `UltraPlayer` object is null [here](https://github.com/iSach/UltraCosmetics/blob/f4115bdf9e3c1ef0bb6e46332d2ce56ef0185b1d/core/src/main/java/be/isach/ultracosmetics/listeners/PlayerListener.java#L257).

**Comment by datatags** [comment]
The PlayerDeathEvent listener now makes sure the death isn't an NPC death. As for this happening without Citizens installed, I don't know why that could be, so please open a new issue if it's still a problem.
