### ISSUE TITLE
onDisable Exception

### ISSUE THREAD

**Issue by iBuseWinner** [iSach/UltraCosmetics#475]
### What steps will reproduce the issue?  
1. Disable server
2. See exception

### What was supposed to happen?

No exceptions in console

### What happened? 

Exceptions in console

### What version of UltraCosmetics are you using?  

2.5.7

### What Spigot version are you using? Paste the output of /version below.  

[21:54:38 INFO]: This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:54:38 INFO]: Checking version, please wait...
[21:54:38 INFO]: You are 8 version(s) behind

### What plugins do you have installed? Paste the output of /plugins below.  

[21:54:51 INFO]: Plugins (20): Chatty*, Citizens, CrazyCrates, DeluxeMenus, DeluxeTags*, DTCoins, DTScoreboard*, Holograms, HologramsPlaceholders*, Joiner, LibsDisguis
PlugMan, ProtocolLib, TAB, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[21:58:05 ERROR]: Error occurred while disabling UltraCosmetics v2.5.7 (Is it up to date?)
java.lang.NullPointerException: null
        at be.isach.ultracosmetics.UltraCosmetics.onDisable(UltraCosmetics.java:238) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:468) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:460) ~[patched_1.15.2.jar:git-Paper-121]
        at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:419) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:379) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:704) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-121]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Billy-Playz** [comment]
You cannot use Plugman (or plugins of the type) with UltraCosmetics.
Please disable it and it will work.

iSach has said on the Discord : 
> Don’t enable it with Plugman
