### ISSUE TITLE
Renaming pet Exception

### ISSUE THREAD

**Issue by iBuseWinner** [iSach/UltraCosmetics#476]
### What steps will reproduce the issue?  
1. Summon pet
2. Try to rename it

### What was supposed to happen?

No exceptions in console; can rename pet

### What happened? 

Exceptions in console; can't rename pet

### What version of UltraCosmetics are you using?  

2.5.7

### What Spigot version are you using? Paste the output of /version below.  

[21:54:38 INFO]: This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:54:38 INFO]: Checking version, please wait...
[21:54:38 INFO]: You are 8 version(s) behind

### What plugins do you have installed? Paste the output of /plugins below.  

[21:54:51 INFO]: Plugins (20): Chatty*, Citizens, CrazyCrates, DeluxeMenus, DeluxeTags*, DTCoins, DTScoreboard*, Holograms, HologramsPlaceholders*, Joiner, LibsDisguis
PlugMan, ProtocolLib, TAB, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[22:31:14 WARN]: java.lang.reflect.InvocationTargetException
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[22:31:14 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[22:31:14 WARN]:        at be.isach.ultracosmetics.version.VersionManager.newAnvilGUI(VersionManager.java:94)
[22:31:14 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.renamePet(MenuPets.java:86)
[22:31:14 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.lambda$addPetRenameItem$0(MenuPets.java:56)
[22:31:14 WARN]:        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133)
[22:31:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor337.execute(Unknown Source)
[22:31:14 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:31:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:31:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:31:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2329)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[22:31:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[22:31:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[22:31:14 WARN]: Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set final int field net.minecraft.server.v1_15_R1.Container.windowId t
[22:31:14 WARN]:        at be.isach.ultracosmetics.v1_15_R1.AnvilGUI.openInventory(AnvilGUI.java:118)
[22:31:14 WARN]:        at be.isach.ultracosmetics.v1_15_R1.AnvilGUI.<init>(AnvilGUI.java:86)
[22:31:14 WARN]:        ... 27 more
[22:31:14 WARN]: Caused by: java.lang.IllegalAccessException: Can not set final int field net.minecraft.server.v1_15_R1.Container.windowId to java.lang.Integer
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[22:31:14 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.set(UnsafeQualifiedIntegerFieldAccessorImpl.java:79)
[22:31:14 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:780)
[22:31:14 WARN]:        at be.isach.ultracosmetics.v1_15_R1.AnvilGUI.openInventory(AnvilGUI.java:116)
[22:31:14 WARN]:        ... 28 more
```
### Any additional information that you would like to provide that may be relevant to the issue?

![image](https://user-images.githubusercontent.com/44753872/76170710-7e95f680-6195-11ea-99bc-7277b2fa637b.png)
![image](https://user-images.githubusercontent.com/44753872/76170713-86559b00-6195-11ea-8aae-cd7ef0a77c8f.png)

**Comment by datatags** [comment]
Same as #525, use Java 11 or lower on 1.16.5 and below.
