### ISSUE TITLE
Exception being thrown whenever using cosmetic

### ISSUE THREAD

**Issue by Matthew-Ramsey** [iSach/UltraCosmetics#487]
### What steps will reproduce the issue?  
1.  Pretty much using any cosmetic in the GUI
2. 
3. 

### What was supposed to happen?
Not thrown an error
### What happened? 
An error was thrown
### What version of UltraCosmetics are you using?  
Latest
### What Spigot version are you using? Paste the output of /version below.  
paper-229
### What plugins do you have installed? Paste the output of /plugins below.  
no ty.
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
`
[16:48:29 WARN]: java.lang.NoSuchFieldException: f
[16:48:29 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[16:48:29 WARN]:        at be.isach.ultracosmetics.v1_15_R1.PathfinderUtil.removePathFinders(PathfinderUtil.java:60)
[16:48:29 WARN]:        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:108)
[16:48:29 WARN]:        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:63)
[16:48:29 WARN]:        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:55)
[16:48:29 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.toggleOn(MenuPets.java:154)
[16:48:29 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.toggleOn(MenuPets.java:34)
[16:48:29 WARN]:        at be.isach.ultracosmetics.menu.CosmeticMenu.lambda$open$1(CosmeticMenu.java:183)
[16:48:29 WARN]:        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133)
[16:48:29 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor217.execute(Unknown Source)
[16:48:29 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:29 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2352)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035)
[16:48:29 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950)
[16:48:29 WARN]:        at java.lang.Thread.run(Thread.java:748)
`
```

**Comment by datatags** [comment]
Can't reproduce. `f` appears to be the correct field, so I'm not sure why this would happen unless the Spigot version was old.
