### ISSUE TITLE
Error appears when the server is closing

### ISSUE THREAD

**Issue by itaquito** [iSach/UltraCosmetics#492]
### What steps will reproduce the issue?  
1. Close the server

### What was supposed to happen?
An error shouldn't appear when the server closes.

### What happened? 
An error appeared when the server closed.
Error: https://pastebin.com/rBFhWHSb

### What version of UltraCosmetics are you using?  
UltraCosmetics-2.5.7-RELEASE

### What Spigot version are you using? Paste the output of /version below.  
```
[16:54:59 INFO]: Checking version, please wait...
[16:54:59 INFO]: This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[16:55:00 INFO]: You are 11 version(s) behind
[16:55:00 INFO]: Previous version: git-Paper-217 (MC: 1.15.2)
```
### What plugins do you have installed? Paste the output of /plugins below.  
`[16:55:16 INFO]: Plugins (29): AdvancedPortals, BungeeTabListPlus, Citizens, CustomJoinMessages*, DeluxeMenus, Essentials, FastAsyncWorldEdit, FeatherBoard*, HolographicDisplays, HolographicExtension, ItemJoin, JumpPads, LeakParkour, LevelPoints, LoginStreak, LuckPerms, MVdWPlaceholderAPI*, PlaceholderAPI, Plan, ProtocolLib, SetTheSpawn, SuperVanish, TreysDoubleJump, UltraCosmetics, Vault, VoidGenerator, VoidSpawn, WorldEdit, WorldGuard`
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[16:47:20 INFO]: [UltraCosmetics] Disabling UltraCosmetics v2.5.7
[16:47:20 ERROR]: Error occurred while disabling UltraCosmetics v2.5.7 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-334]
        at be.isach.ultracosmetics.UltraCosmetics.onDisable(UltraCosmetics.java:238) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:406) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:1008) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-334]
```
### Any additional information that you would like to provide that may be relevant to the issue?
No, thanks.

**Comment by datatags** [comment]
Guess this was fixed at some point?
