### ISSUE TITLE
UltraCosmetics can't keep a stable connection open with MariaDB

### ISSUE THREAD

**Issue by Permanently** [iSach/UltraCosmetics#507]
### What steps will reproduce the issue?  
1. Install UltraCosmetics on any version.
2. Connect it to a MariaDB server.
3. Observe.

### What was supposed to happen?
For the plugin to stay connect to the database server.

### What happened? 
The exact opposite.

### What version of UltraCosmetics are you using?  
2.5.8

### What Spigot version are you using? Paste the output of /version below.  
Not relevant.

### What plugins do you have installed? Paste the output of /plugins below.  
Not relevant.

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[12:57:30] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 713,675 milliseconds ago.  The last packet sent successfully to the server was 713,675 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[12:57:30] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor107.newInstance(Unknown Source)
[12:57:30] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:57:30] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
[12:57:30] [Server thread/WARN]: 	at be.isach.ultracosmetics.mysql.SelectQuery.execute(SelectQuery.java:43)
[12:57:30] [Server thread/WARN]: 	at be.isach.ultracosmetics.mysql.SqlUtils.initStats(SqlUtils.java:31)
[12:57:30] [Server thread/WARN]: 	at be.isach.ultracosmetics.player.UltraPlayer.<init>(UltraPlayer.java:126)
[12:57:30] [Server thread/WARN]: 	at be.isach.ultracosmetics.player.UltraPlayerManager.create(UltraPlayerManager.java:39)
[12:57:30] [Server thread/WARN]: 	at be.isach.ultracosmetics.listeners.PlayerListener.onJoin(PlayerListener.java:52)
[12:57:30] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source)
[12:57:30] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[12:57:30] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:57:30] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:57:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[12:57:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[12:57:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:57:30] [Server thread/WARN]: Caused by: java.net.SocketException: Connection reset
[12:57:30] [Server thread/WARN]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
[12:57:30] [Server thread/WARN]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
[12:57:30] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[12:57:30] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[12:57:30] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728)
[12:57:30] [Server thread/WARN]: 	... 26 more
```
Occasionally you get the `UltraCosmetics -> Successfully connected to MySQL server! :)` again a little while after those errors, but if someone tries to use the chest whilst it's disconnected from the DB server, more errors are spammed in the console. And, just because it's "successfully connected", doesn't mean it won't disconnect again 15 minutes later.

### Any additional information that you would like to provide that may be relevant to the issue?
1. Add drivers for other servers such as PostgreSQL, MariaDB, etc.
2. Allow us to modify the MySQL arguments in the configuration. E.g. `useSSL=true`.

**Comment by datatags** [comment]
Should be fixed in the latest commits with a switch to Hikari.
