### ISSUE TITLE
Emote head dupe glitch

### ISSUE THREAD

**Issue by JackCrispy** [iSach/UltraCosmetics#515]
### What steps will reproduce the issue?  
1. Go to emote menu
2. Put on a hat, like angry
3. Go to inv & rigt shift click on the head, it goes to your inv

### What was supposed to happen?
It doesn't duplicate the emote head.

### What happened? 
It dupes the emote head into your inv. You can do it as many times as needed.

### What version of UltraCosmetics are you using?  
2.5.9-RELEASE

### What Spigot version are you using? Paste the output of /version below.  
https://i.crisp.codes/67da9b.png

### What plugins do you have installed? Paste the output of /plugins below.  
https://i.crisp.codes/9581e5.png
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
N/A

**Comment by datatags** [comment]
Relevant error I'm getting:
```
[11:12:59 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.5.11
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.equals(Object)" because "this.serializedProfile" is null
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaSkull.equalsCommon(CraftMetaSkull.java:238) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:316) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemFactory.equals(CraftItemFactory.java:303) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:294) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack.isSimilar(CraftItemStack.java:564) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.inventory.ItemStack.equals(ItemStack.java:275) ~[patched_1.17.1.jar:git-Paper-358]
        at be.isach.ultracosmetics.cosmetics.emotes.Emote.onInventoryClick(Emote.java:54) ~[UltraCosmetics-2.5.11-RELEASE.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor441.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-358]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-358]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2807) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1372) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Paper-358]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-358]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
