### ISSUE TITLE
SPECIFIC MOUNT CRASHES SERVER ON 1.16.3 PURPUR

### ISSUE THREAD

**Issue by DiegoDaniel** [iSach/UltraCosmetics#520]
Mount the red flying snake.
```
[20:14:59 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Exception ticking world
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1445) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-802]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2086) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.g(PlayerChunkMap.java:2105) ~[patched_1.16.3.jar:git-Purpur-802]        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1067) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:892) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429) ~[patched_1.16.3.jar:git-Purpur-802]
        ... 5 more
[20:14:59 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException: null
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2086) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.g(PlayerChunkMap.java:2105) ~[patched_1.16.3.jar:git-Purpur-802]        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1067) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:892) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1429) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:381) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1280) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.3.jar:git-Purpur-802]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-802]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[20:14:59 ERROR]: This crash report has been saved to: C:\Users\Galar\Desktop\Bungee Server\Server_HUB\.\crash-reports\crash-2020-10-26_20.14.59-server.txt
```

**Comment by datatags** [comment]
Not much information was provided here. Many issues with the molten snake seem to have been fixed already, but if it's still an issue, please reopen with your current:
- UC version
- Minecraft server version
- Minecraft server distribution (Spigot, Paper, etc.)
