### ISSUE TITLE
Error when renaming the pet

### ISSUE THREAD

**Issue by sergyops** [iSach/UltraCosmetics#525]
### What steps will reproduce the issue?  
1. Change pets-name enabled = true
2. change pet name in gui

### What was supposed to happen?

The pet's name changes

### What happened?

shows an error in the console, the name does not change and the player is given a paper with the name of "pet name"

### What version of UltraCosmetics are you using? 

2.5.10

### What Spigot version are you using? Paste the output of /version below.

Previous version: git-Paper-298 (MC: 1.16.4)

### What plugins do you have installed? Paste the output of /plugins below. 

AdvancedHelp, AnimatedScoreboard, antiRedstoneClock, AsyncWorldEdit, AuctionHouse, AureliumSkills, CombatLogX, CommandTimer*, CommandWhitelist, ConsoleSpamFix, CoreProtect, eBackup, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GoldenCrates, GUIShop, HeadHunter, Jobs, LuckPerms, Multiverse-Core, MyCommand, NexEngine, PlaceholderAPI, ProtectionStones, ProtocolLib, RandomTeleport, StackMob, TAB, UltraCosmetics, Vault, WorldBorder, WorldEdit, WorldGuard, ZNPCS

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[17:47:10 WARN]: java.lang.reflect.InvocationTargetException
[17:47:10 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:47:10 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[17:47:10 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:47:10 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[17:47:10 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[17:47:10 WARN]:        at be.isach.ultracosmetics.version.VersionManager.newAnvilGUI(VersionManager.java:94)
[17:47:10 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.renamePet(MenuPets.java:86)
[17:47:10 WARN]:        at be.isach.ultracosmetics.menu.menus.MenuPets.lambda$addPetRenameItem$3(MenuPets.java:71)
[17:47:10 WARN]:        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:133)
[17:47:10 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor142.execute(Unknown Source)
[17:47:10 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:47:10 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:47:10 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:47:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2530)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[17:47:10 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[17:47:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[17:47:10 WARN]: Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: modifiers
[17:47:10 WARN]:        at be.isach.ultracosmetics.v1_16_R3.AnvilGUI.openInventory(AnvilGUI.java:118)
[17:47:10 WARN]:        at be.isach.ultracosmetics.v1_16_R3.AnvilGUI.<init>(AnvilGUI.java:86)
[17:47:10 WARN]:        ... 29 more
[17:47:10 WARN]: Caused by: java.lang.NoSuchFieldException: modifiers
[17:47:10 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2569)
[17:47:10 WARN]:        at be.isach.ultracosmetics.v1_16_R3.AnvilGUI.openInventory(AnvilGUI.java:112)
[17:47:10 WARN]:        ... 30 more
```
### Any additional information that you would like to provide that may be relevant to the issue?
Nothing

**Comment by datatags** [comment]
Renaming is also broken in v1_18_R1, but with a different error:
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "be.isach.ultracosmetics.version.AAnvilGUI$Response.getText()" is null
        at be.isach.ultracosmetics.v1_18_R1.AnvilGUI$ListenUp.onInventoryClick(AnvilGUI.java:254) ~[UltraCosmetics-2.6-DEV-b5.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-150]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2834) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-150]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-150]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by datatags** [comment]
Turns out the error I posted is completely unrelated. To solve the issue in the OP, use Java 11 or less.
