### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ParadoX4** [iSach/UltraCosmetics#53]
Please help...What this means ?
```
> [23:40:43 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Ticking entity
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_8_R3.Path.b(Path.java:100) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Path.c(Path.java:38) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:37) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:27) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:71) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:77) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.PathfinderGoalRandomStroll.c(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:69) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntitySheep.m(EntitySheep.java:63) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

... 4 more
> [23:40:43 ERROR]: Cause of unexpected exception was
java.lang.NullPointerException
at net.minecraft.server.v1_8_R3.Path.b(Path.java:100) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Path.c(Path.java:38) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:37) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.Pathfinder.a(SourceFile:27) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:71) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.NavigationAbstract.a(SourceFile:77) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.PathfinderGoalRandomStroll.c(SourceFile:56) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:69) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1626) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntitySheep.m(EntitySheep.java:63) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-3f3c65f]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
> [23:40:43 ERROR]: This crash report has been saved to: /hlserver/27416/./crash-reports/crash-2016-02-18_23.40.43-server.txt
> [23:40:43 INFO]: Stopping server
```

**Comment by Noodles0809** [comment]
This does not look like this plugin error

**Comment by JHXSMatthew** [comment]
Hi, that's navigation error for nyan sheep. Try to upgrade spigot to latest version.  If you still have this frequently, disable the mount for now. sorry for inconvenience.

**Comment by iSach** [comment]
As said @JHXSMatthew This is a Minecraft's navigation error. :/
