### ISSUE TITLE
Yatopia nullpointer error

### ISSUE THREAD

**Issue by TheDevTec** [iSach/UltraCosmetics#530]
### What happened? 
Null pointer error in console

### What version of UltraCosmetics are you using?  
2.5.10

### What Spigot version are you using? Paste the output of /version below.  
git-Yatopia-"d072a35" (MC: 1.16.4)

### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (29): ajParkour, ArmorStandEditor, AsInteract, AuthMe, BungeeUtility, Citizens, CitizensCMD, CraftingStore, DeluxeHub, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, HolographicPlaceholders, ImageMaps, LuckPerms, PlaceholderAPI, PlugMan, ProtocolLib, ServerControlReloaded, TAB, TheAPI, UltimateCachinator, UltraCosmetics, Vault, ViaBackwards, ViaVersion, VIPSystem, Votifier, WorldBorder, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[13:28:14 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.5.10
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSkull.equalsCommon(CraftMetaSkull.java:235) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemFactory.equals(CraftItemFactory.java:306) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemFactory.equals(CraftItemFactory.java:293) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:293) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.isSimilar(CraftItemStack.java:554) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.inventory.ItemStack.equals(ItemStack.java:274) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at be.isach.ultracosmetics.cosmetics.emotes.Emote.onInventoryClick(Emote.java:57) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor457.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2528) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Tuinity-"cc34294"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Comment by MWHunter** [comment]
Same error on the airplane jar.

**Comment by datatags** [comment]
Fixed in dev builds which are on the Discord.
