### ISSUE TITLE
Rocket broken after being used 

### ISSUE THREAD

**Issue by sasi2006166** [iSach/UltraCosmetics#533]
[11:47:39 WARN]: [UltraCosmetics] Plugin UltraCosmetics v2.5.10 generated an exception while executing task 16513
java.lang.IndexOutOfBoundsException: Index: 9, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_275]
        at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_275]
        at be.isach.ultracosmetics.cosmetics.gadgets.GadgetRocket.onUpdate(GadgetRocket.java:202) ~[?:?]
        at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.run(Gadget.java:143) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]

**Comment by datatags** [comment]
I couldn't completely reproduce the issue but it should be fixed in dev builds, which are found in the Discord.
