### ISSUE TITLE
WorldGuard mob-spawning flags disabling upon pet equip

### ISSUE THREAD

**Issue by ImaGorilla** [iSach/UltraCosmetics#535]
### What steps will reproduce the issue?  
1. Have WorldGuard installed with a region defined with the flag mob-spawning deny
2. Equip a pet.
3. Witness error message in console
4. Watch as animals and monsters are now able to spawn. You can even use /spawnmob to spawn them, when you shouldn't be able to
If this doesn't work, more specifically, try reconnecting with a pet equipped and the config set to automatically respawn your pets upon reconnect. That definitely made it happen.

### What was supposed to happen?
Pet was supposed to be equipped without breaking worldguard mob-spawning flag.

### What happened? 
Pet was equipped and the worldguard mob-spawning flag for every single world, including the one the pet was in and ones the pet was not in, broke.

### What version of UltraCosmetics are you using?  
UltraCosmetics 2.5.10

### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-PaperSpigot-8fb8e031 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
https://gyazo.com/57358fddd0db14e92062f4821f1dc5cd

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
User connects to server with pet equipped. This error message shows right when the worldguard flags break.

[03:50:40] [User Authenticator #62/INFO]: UUID of player EmphaticChief4 is 9903a555-a84d-4a68-8ebf-248a90e7a8f0
[03:50:40] [Netty Epoll Server IO #1/WARN]: [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
[03:50:40] [Server thread/INFO]: EmphaticChief4[/24.185.222.73:62584] logged in with entity id 10433580 at ([Spawn]-0.598726849190131, 186.0, 25.99306198151091)
[03:50:40] [Server thread/INFO]: [0;30;1m[[0;36;1m+[0;30;1m] [0;37;22mEmphaticChief4[m
[03:50:40] [Craft Scheduler Thread - 2170/WARN]: Exception in thread "Craft Scheduler Thread - 2170" 
[03:50:40] [Craft Scheduler Thread - 2170/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v2.5.10 generated an exception while executing task 3541897
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:996)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.addEntity(CraftWorld.java:1160)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.spawn(CraftWorld.java:1167)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.spawn(CraftWorld.java:884)
	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.spawnEntity(CraftWorld.java:402)
	at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:88)
	at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:63)
	at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:55)
	at be.isach.ultracosmetics.player.profile.CosmeticsProfile.loadToPlayer(CosmeticsProfile.java:127)
	at be.isach.ultracosmetics.player.profile.CosmeticsProfileManager.initForPlayer(CosmeticsProfileManager.java:54)
	at be.isach.ultracosmetics.listeners.PlayerListener$1.run(PlayerListener.java:75)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 4 more

[03:50:40] [Server thread/WARN]: java.lang.NullPointerException
[03:50:40] [Server thread/WARN]: 	at be.isach.ultracosmetics.cosmetics.pets.Pet.onUpdate(Pet.java:218)
[03:50:40] [Server thread/WARN]: 	at be.isach.ultracosmetics.cosmetics.pets.Pet.run(Pet.java:144)
[03:50:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[03:50:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[03:50:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771)
[03:50:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[03:50:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701)
[03:50:40] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604)
[03:50:40] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by datatags** [comment]
Fixed in dev builds, which you can find on the Discord.
