### ISSUE TITLE
error getting that :

### ISSUE THREAD

**Issue by el211** [iSach/UltraCosmetics#551]
### What steps will reproduce the issue?  
i am running geysermc 
1.17.1 

am getting that error 👍 
[18:07:27 WARN]: [UltraCosmetics] Task #7980225 for UltraCosmetics v2.5.11 generated an exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.pathfinder.PathEntity net.minecraft.world.entity.ai.navigation.NavigationAbstract.a(double, double, double, int)'
        at be.isach.ultracosmetics.v1_17_R1.EntityUtil.follow(EntityUtil.java:330) ~[UltraCosmetics-2.5.11-RELEASE.jar:?]
        at be.isach.ultracosmetics.cosmetics.morphs.MorphChicken$1.run(MorphChicken.java:71) ~[UltraCosmetics-2.5.11-RELEASE.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-311]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-311]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-311]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
paste
error(s)
here
```

**Comment by datatags** [comment]
You didn't fill out the issue template, but this is not an issue with UC anyway. This is a bug with Paper, the plugin works fine on Spigot. See: https://github.com/PaperMC/paperweight/issues/24
