### ISSUE TITLE
[Server thread/ERROR]: Could not pass event PlayerDeathEvent to UltraCosmetics v2.6-RELEASE

### ISSUE THREAD

**Issue by NBCSMgithub** [iSach/UltraCosmetics#584]
### What steps will reproduce the issue?

1. tbh dunno whats causing this
2. 
3. 

### What was supposed to happen?

-

### What happened instead?

-

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-2.6-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Spigot 1.8.8

### What plugins do you have installed?

Essentials, Duels, Vault, UltraCosmetics

### Are there any errors in the console or in logs?

[Server thread/ERROR]: Could not pass event PlayerDeathEvent to UltraCosmetics v2.6-RELEASE
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[FACTION.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[FACTION.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FACTION.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FACTION.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FACTION.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) ~[FACTION.jar:]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:425) ~[FACTION.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:89) ~[FACTION.jar:]
	at me.realized.duels.duel.DuelManager$DuelListener.on(DuelManager.java:727) ~[Duels-3.4.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor848.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[FACTION.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[FACTION.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[FACTION.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[FACTION.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[FACTION.jar:]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:364) ~[FACTION.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:875) ~[FACTION.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.disconnect(PlayerConnection.java:186) ~[FACTION.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:314) ~[FACTION.jar:]
	at com.earth2me.essentials.commands.Commandkick.run(Commandkick.java:51) ~[EssentialsX-2.19.0.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:174) ~[EssentialsX-2.19.0.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:766) ~[EssentialsX-2.19.0.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:671) ~[EssentialsX-2.19.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[FACTION.jar:]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[FACTION.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[FACTION.jar:]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:596) ~[FACTION.jar:]
	at java.util.ArrayList.forEach(ArrayList.java:1259) [?:1.8.0_322]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [FACTION.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [FACTION.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [FACTION.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) [FACTION.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [FACTION.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [FACTION.jar:]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: java.lang.NullPointerException
	at be.isach.ultracosmetics.listeners.PlayerListener.onDeath(PlayerListener.java:250) ~[UltraCosmetics-2.6-RELEASE.jar:?]
	at sun.reflect.GeneratedMethodAccessor766.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_322]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_322]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[FACTION.jar:]
	... 39 more

**Comment by datatags** [comment]
Caused by another plugin announcing a Player Death Event after the player has logged out. Kinda weird but I'll see about a workaround.

**Comment by datatags** [comment]
Please try the dev build here once it's done: https://github.com/iSach/UltraCosmetics/actions/runs/1974965898
