### ISSUE TITLE
MySQL Data loading task error

### ISSUE THREAD

**Issue by JAHMCR** [iSach/UltraCosmetics#592]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Enable MySQL in config.yml
2. Start the server
3. Join the server
4. Stop the server
5. Start the server

### What was supposed to happen?

No errors in console while loading SQL data

### What happened instead?

There is an error in the console when loading SQL data

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics 2.6.1 DEV b11

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper build 216

### What plugins do you have installed?

Plugins (19): CMILib, CoreProtect, Essentials, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, Jobs, mcMMO, Multiverse-Core, PlaceholderAPI, ResourceWorld, Shops, SkinsRestorer, UltraCosmetics, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Are there any errors in the console or in logs?

[02:21:37] [Craft Scheduler Thread - 8 - UltraCosmetics/WARN]: Plugin UltraCosmetics v2.6.1-DEV-b11 generated an exception while executing task 1143
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Boolean (java.lang.Integer and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at be.isach.ultracosmetics.player.profile.PlayerData.loadFromSQL(PlayerData.java:196) ~[UltraCosmetics-2.6.1-DEV-b11.jar:?]
        at be.isach.ultracosmetics.mysql.SqlCache.load(SqlCache.java:40) ~[UltraCosmetics-2.6.1-DEV-b11.jar:?]
        at be.isach.ultracosmetics.player.profile.CosmeticsProfile.lambda$new$1(CosmeticsProfile.java:32) ~[UltraCosmetics-2.6.1-DEV-b11.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [paper-1.18.2.jar:git-Paper-267]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paper-1.18.2.jar:git-Paper-267]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]

### Additional information that could be helpful in fixing the problem

Checking the code, I see the issue is in this line of code:

gadgetsEnabled = (boolean) properties.get(ProfileKey.GADGETS_ENABLED.getSqlKey());

To fix the issue you could:

1) Modify the "gadgetsEnabled" column to be BOOLEAN
2) Modify the line to: "gadgetsEnabled = properties.get(ProfileKey.GADGETS_ENABLED.getSqlKey()).equals(1);"

I guess after fixing this, the same issue will happen with this other line:

morphSelfView = (boolean) properties.get(ProfileKey.MORPH_VIEW.getSqlKey());

So you could just do the same as above

**NVM just tried to change the column type to be BOOLEAN (TINYINT) but still fails, so you should do the second option**

**Comment by datatags** [comment]
That's interesting, out of curiosity what database backend are you using? (MySQL Server, MariaDB, etc?)

**Comment by datatags** [comment]
I believe I've fixed it, but I couldn't reproduce the issue so I'm not 100% sure. Please let me know if [this build](https://github.com/iSach/UltraCosmetics/actions/runs/2038599364) fixes it (same build mentioned in other issue)

**Comment by JAHMCR** [comment]
Thanks, will test the latest DEV build. I'm using MySQL 8
