### ISSUE TITLE
Fresh startup. Log error, no config.

### ISSUE THREAD

**Issue by LigerXT5** [iSach/UltraCosmetics#60]
I recently tried to use the plugin. On startup, I receive the following error.
`[16:18:21] [Server thread/ERROR]: Error occurred while enabling UltraCosmetics v2.0.7 (Is it up to date?)
java.lang.NoClassDefFoundError: me/libraryaddict/disguise/disguisetypes/DisguiseType
	at be.isach.ultracosmetics.cosmetics.morphs.MorphType.<clinit>(MorphType.java:21) ~[?:?]
	at be.isach.ultracosmetics.util.GeneralUtil.printPermissions(GeneralUtil.java:74) ~[?:?]
	at be.isach.ultracosmetics.UltraCosmetics.onEnable(UltraCosmetics.java:637) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: me.libraryaddict.disguise.disguisetypes.DisguiseType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-db6de12-3f3c65f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	... 14 more`

As far as I know, there is no other plugin requirement for this, am I correct?

**Comment by JHXSMatthew** [comment]
Hi, if you want morph to be enabled, you need Lib's disguise and Protocol lib.
Otherwise, disable morph.
Read the wiki first.
Cheers

**Comment by LigerXT5** [comment]
Sorry, I completely forgot to mention, there is no config being generated. I have nothing to alter.

**Comment by JHXSMatthew** [comment]
Could you try with Lib's disguise plugin installed ?
I cannot confirm this issue.
Cheers.

**Comment by cwchristerw** [comment]
This happened to me when used latest LibsDisguises
https://ci.md-5.net/job/LibsDisguises/lastSuccessfulBuild/
