### ISSUE TITLE
Null exception when click on menu

### ISSUE THREAD

**Issue by dejwideek-dev** [iSach/UltraCosmetics#610]
### Check if the issue is fixed in dev builds

- [x] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Just open UC menu and click any slot.

### What was supposed to happen?

line 118 in Menu.java class

### What happened instead?

print error in console

### What version of UltraCosmetics are you using? Do not say 'latest'.

2.7-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Paper fork 1.8.8

### What plugins do you have installed?

Plugins (39): ServerQueue, lobbyutils, Memory, SlimeWorldManager, JumpPads, PlaceholderAPI, DisableJoinMessage, SpawnJoin, ChangeSlots, commands, VoidSpawn, asCMD, MVdWPlaceholderAPI, FastAsyncWorldEdit, CombatElite, djw-LobbyItemsFix, core, NoteBlockAPI, slots, ViaVersion, CustomJoinItems, Vault, ViaBackwards, JukeBox, ViaRewind, WorldEdit, ViaRewind-Legacy-Support, ProtocolLib, WorldGuard, Citizens, SkinsRestorer, BungeeGuard, DeluxeMenus, TAB, SimpleScore, UltraCosmetics, HolographicDisplays, CitizensCMD, HolographicExtension

### Are there any errors in the console or in logs?

[12:42:30 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v2.7-RELEASE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:778) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:387) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:717) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:620) [patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:118) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-ArcadePaper-e884650git-Spigot-c5bb3dc-741a1bd]
        ... 16 more

**Comment by datatags** [comment]
"No longer an issue"
