### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SmartSoda** [iSach/UltraCosmetics#62]
No plugins other than Vault and UltraCosmetics 2.0.7

[17:48:25 INFO]: [UltraCosmetics] Enabling UltraCosmetics v2.0.7
[17:48:25 INFO]: UltraCosmetics -> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[17:48:25 INFO]: UltraCosmetics -> UltraCosmetics v2.0.7 is being loaded...
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Thanks for having downloaded it!
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Plugin by iSach.
[17:48:25 INFO]: UltraCosmetics -> Link: http://bit.ly/UltraCosmetics
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Loading configuration...
[17:48:25 INFO]: UltraCosmetics -> Configuration loaded.
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Registering Custom Entities...
[17:48:25 INFO]: UltraCosmetics -> Custom Entities registered.
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Preparing Metrics data.
[17:48:25 INFO]: UltraCosmetics -> Data sent to Metrics successfully.
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Registering Messages...
[17:48:25 INFO]: UltraCosmetics -> Messages registered.
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 INFO]: UltraCosmetics -> Registering commands...
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'gadgets'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'selfview'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'menu'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'give'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'toggle'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'clear'
[17:48:25 INFO]: UltraCosmetics ->   Registered subcommand 'treasure'
[17:48:25 INFO]: UltraCosmetics -> Registered command: '/ultracosmetics'.
[17:48:25 INFO]: UltraCosmetics -> Registered command: '/uc'.
[17:48:25 INFO]: UltraCosmetics -> Registered commands.
[17:48:25 INFO]: UltraCosmetics -> 
[17:48:25 ERROR]: Error occurred while enabling UltraCosmetics v2.0.7 (Is it up to date?)
java.lang.NullPointerException
        at be.isach.ultracosmetics.UltraCosmetics.onEnable(UltraCosmetics.java:515) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:741) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]

**Comment by SmartSoda** [comment]
Nevermind, corrupt configuration I suppose.
