### ISSUE TITLE
You must be on the ground (ViaVersion 1.9)

### ISSUE THREAD

**Issue by HAlexTM** [iSach/UltraCosmetics#69]
Hi, everything works fine, just a thing: using 1.9 client on spigot-1.8.8 you must click on Treasure chest hundreds of times before get it open, in the meantime I get this message: You must be on the ground!

Everything is fine using 1.8 client, thanks for all.

**Comment by HAlexTM** [comment]
This is a random error in the console, as I've read "Rocket" I think that is related (even if the error is with Treasure chests)

`[UltraCosmetics] Task #1832065 for UltraCosmetics v2.1 generated an exception
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.EXPLODe
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_66]        at org.bukkit.Sound.valueOf(Sound.java:1) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at be.isach.ultracosmetics.cosmetics.gadgets.GadgetRocket$2$1$1.run(GadgetRocket.java:151) ~[?:?]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
`

**Comment by BlazeBoy** [comment]
I have the same problem too

**Comment by HAlexTM** [comment]
Mine too, anyway on a good place (5x5) and 1.8 works flawlessly

**Comment by JHXSMatthew** [comment]
Sound error shoud be fixed, looking into viaversion location problem.
