### ISSUE TITLE
Treasure Chest Problems!

### ISSUE THREAD

**Issue by zobos** [iSach/UltraCosmetics#72]
This was fine when my server was running 1.8 now its broken, The treasure chest system spits out a huge bunch of errors when trying to open a chest here is the log:

----------<LOG START>----------
[15:13:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'uc' in plugin UltraCosmetics v2.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1342) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1177) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-6f291ea-55a8535]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/World
        at be.isach.ultracosmetics.manager.TreasureChestManager.openTreasureChest(TreasureChestManager.java:31) ~[?:?]
        at be.isach.ultracosmetics.manager.TreasureChestManager.tryOpenChest(TreasureChestManager.java:60) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.TreasureCommand.common(TreasureCommand.java:76) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.TreasureCommand.onExePlayer(TreasureCommand.java:25) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:97) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
        at be.isach.ultracosmetics.manager.TreasureChestManager.openTreasureChest(TreasureChestManager.java:31) ~[?:?]
        at be.isach.ultracosmetics.manager.TreasureChestManager.tryOpenChest(TreasureChestManager.java:60) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.TreasureCommand.common(TreasureCommand.java:76) ~[?:?]
        at be.isach.ultracosmetics.command.subcommands.TreasureCommand.onExePlayer(TreasureCommand.java:25) ~[?:?]
        at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:97) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6f291ea-55a8535]
        ... 15 more
----------<LOG END>----------

Any solutions?

**Comment by iSach** [comment]
Sorry for really long delay of reply... :/
Fixed or not? If no,please reopen.
