### ISSUE TITLE
Slime mount

### ISSUE THREAD

**Issue by Mineteamhost** [iSach/UltraCosmetics#73]
Hi,
I've a problem with the plugin, when I select the slime mount nothing happens and I get this error in the server's console:
`[19:01:07] [Server thread/WARN]: java.lang.NoSuchMethodException: be.isach.ultracosmetics.cosmetics.mounts.MountCustomEntity_1_8_R3.<init>(java.util.UUID)
[19:01:07] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[19:01:07] [Server thread/WARN]: 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[19:01:07] [Server thread/WARN]: 	at be.isach.ultracosmetics.cosmetics.mounts.MountType.equip(MountType.java:154)
[19:01:07] [Server thread/WARN]: 	at be.isach.ultracosmetics.manager.MountManager$3.run(MountManager.java:167)
[19:01:07] [Server thread/WARN]: 	at be.isach.ultracosmetics.manager.MountManager.equipMount(MountManager.java:164)
[19:01:07] [Server thread/WARN]: 	at be.isach.ultracosmetics.manager.MountManager.mountsSelection(MountManager.java:239)
[19:01:07] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[19:01:07] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:01:07] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:01:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[19:01:07] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:01:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[19:01:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:01:07] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:01:07] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:01:07] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[19:01:07] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
`
What is the problem?
Thanks 
Mineteam

**Comment by iSach** [comment]
Hello,
again a issue I didn't reply to, I should be ashamed, sorry for that. Still not fixed? If no, please reopen.
